# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SwpBannerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for SwpBannerDemo
  pod 'SwpBanner', :path => '../'
  pod 'Masonry',  :inhibit_warnings => true

end
